---
dist: bionic

language: node_js
node_js: 14

cache:
  npm: false

script:
  - npm run lint-ci
  - npm run tsc
  - npm run build
  - bash mk/build-website.sh

deploy:
  - provider: pages
    edge: true
    token: $GITHUB_TOKEN
    keep_history: false
    commit_message: $TRAVIS_COMMIT $TRAVIS_BUILD_WEB_URL
    local_dir: public/
    fqdn: nfd-status-page.ndn.today
