name: build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: corepack pnpm install
      - name: Check code style
        run: |
          corepack pnpm lint
          git diff --exit-code
      - run: corepack pnpm typecheck
      - run: corepack pnpm build
      - name: Prepare demo site
        run: bash mk/build-website.sh
      - uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: ./public/
          commit_message: ${{ github.sha }} ${{ github.run_id }}
          fqdn: nfd-status-page.ndn.today
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
